### ISSUE TITLE
`neovim`: Create standalone config

### ISSUE THREAD

**Issue by Lehmanator** [Lehmanator/nix-configs#39]
## To-Do

- [ ] Remove `programs.nixvim` prefix from all options in `nixvim`/`neovim` profiles
- [ ] Call top-level `nixvim` config with `makeNixvimConfigWithModules` (or whatever the function name is`.
- [ ] Import standalone config in `home-manager` config.
- [ ] Import in `devShells.*`

## Questions

- [ ] Is it possible to wrap Neovim with Nixvim config, then later apply extra config from `devShells`, `home-manager`, or NixOS system?
